version: '3.8'

services:
  # Наш Backend на FastAPI
  api:
    build: .
    ports:
      - "8000:8000" # Исправили порт под наш фронтенд
    env_file:
      - .env
    depends_on:
      - db
    # Исправили путь запуска на backend.main:app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"